export const MOCK_PRODUCTS = [
  {
    id: '1',
    name: 'Pro Garlic Tap Round Smart Watch',
    price: 7999,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop',
    category: 'Electronics',
    description: 'Latest smart watch with health tracking and notifications',
    rating: 4.5,
    reviews: 156,
    battery: '2000-2499 mAh',
    color: ['black', 'gold', 'silver'],
    inStock: true,
  },
  {
    id: '2',
    name: 'iPhone 17 Pro Max - 2 TB',
    price: 90999,
    image: 'https://images.unsplash.com/photo-1592286927505-1def25115558?w=500&h=500&fit=crop',
    category: 'Electronics',
    description: 'Latest iPhone with advanced camera system',
    rating: 4.8,
    reviews: 432,
    color: ['orange', 'black', 'silver'],
    inStock: true,
  },
  {
    id: '3',
    name: 'Kitchen Storage Set',
    price: 2499,
    image: '',
    category: 'Home & Furniture',
    description: 'Complete kitchen storage solution',
    rating: 4.3,
    reviews: 89,
    inStock: true,
  },
  {
    id: '4',
    name: 'Wireless Earbuds Pro',
    price: 4999,
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
    category: 'Electronics',
    description: 'Premium wireless earbuds with noise cancellation',
    rating: 4.6,
    reviews: 234,
    inStock: true,
  },
  {
    id: '5',
    name: 'Fashion Women Handbag',
    price: 3999,
    image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500&h=500&fit=crop',
    category: 'Women',
    description: 'Stylish leather handbag for everyday use',
    rating: 4.4,
    reviews: 167,
    inStock: true,
  },
  {
    id: '6',
    name: 'Men Casual Watch',
    price: 5999,
    image: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=500&h=500&fit=crop',
    category: 'Men',
    description: 'Classic casual watch with water resistance',
    rating: 4.5,
    reviews: 198,
    inStock: true,
  },
  {
    id: '7',
    name: 'Baby Care Kit',
    price: 1999,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500&h=500&fit=crop',
    category: 'Baby & Kids',
    description: 'Complete baby care essentials',
    rating: 4.7,
    reviews: 312,
    inStock: true,
  },
  {
    id: '8',
    name: 'Refrigerator Organizer',
    price: 1499,
    image: 'https://images.unsplash.com/photo-1584568694244-14fbbc50d737?w=500&h=500&fit=crop',
    category: 'Home & Furniture',
    description: 'Space-saving refrigerator organizer',
    rating: 4.2,
    reviews: 78,
    inStock: true,
  },
  {
    id: '9',
    name: 'Running Shoes Pro',
    price: 6499,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&h=500&fit=crop',
    category: 'Men',
    description: 'Professional running shoes with cushioning',
    rating: 4.6,
    reviews: 287,
    inStock: true,
  },
  {
    id: '10',
    name: 'Women Fitness Tracker',
    price: 3499,
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=500&h=500&fit=crop',
    category: 'Women',
    description: 'Advanced fitness tracking smartwatch',
    rating: 4.4,
    reviews: 145,
    inStock: true,
  },
  {
    id: '11',
    name: 'Smart Home Hub',
    price: 5499,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&h=500&fit=crop',
    category: 'Electronics',
    description: 'Control all your smart home devices',
    rating: 4.5,
    reviews: 221,
    inStock: true,
  },
  {
    id: '12',
    name: 'Portable Speaker',
    price: 3999,
    image: 'https://images.unsplash.com/photo-1589003077984-894e133814c9?w=500&h=500&fit=crop',
    category: 'Electronics',
    description: 'High-quality portable wireless speaker',
    rating: 4.3,
    reviews: 156,
    inStock: true,
  },
]

export const MOCK_CATEGORIES = [
  { id: 'all', name: 'All' },
  { id: 'electronics', name: 'Electronics' },
  { id: 'men', name: 'Men' },
  { id: 'women', name: 'Women' },
  { id: 'baby', name: 'Baby & Kids' },
  { id: 'home', name: 'Home & Furniture' },
  { id: 'offers', name: 'Offers' },
  { id: 'tv', name: 'TV & Appliances' },
]

export const MOCK_USERS = [
  {
    id: '1',
    email: 'user@example.com',
    password: '$2a$10$abcdefghijklmnopqrstuvwxyz', // hashed 'password'
    name: 'Aryan',
    phone: '+91 98765 43210',
    address: '123 Main St, Mumbai, MH 400001',
    role: 'user',
  },
]
